ci: remove default features from threshold-bls in ffi
BLS12-381 does not support certain instructions

```
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`
```